import { Stack } from 'expo-router';
import { Suspense } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';

import { db } from '@/db/client';
// Generated by `npm run db:generate` (runs automatically in the dev container's
// post-create step). If your editor flags this import before first generation,
// run `npm run db:generate` once.
import migrations from '@/drizzle/migrations';

export default function RootLayout() {
  const { success, error } = useMigrations(db, migrations);

  if (error) {
    return (
      <View style={styles.center}>
        <Text style={styles.errorTitle}>Database error</Text>
        <Text style={styles.errorBody}>{error.message}</Text>
      </View>
    );
  }

  if (!success) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" />
        <Text style={styles.muted}>Preparing your database…</Text>
      </View>
    );
  }

  return (
    <SafeAreaProvider>
      <Suspense fallback={<ActivityIndicator size="large" style={{ flex: 1 }} />}>
        <Stack>
          <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
          <Stack.Screen name="brew/new" options={{ title: 'New brew', presentation: 'modal' }} />
        </Stack>
      </Suspense>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 24 },
  muted: { color: '#888' },
  errorTitle: { fontSize: 18, fontWeight: '600', color: '#b00020' },
  errorBody: { color: '#444', textAlign: 'center' },
});
